/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package packagesystem;

import java.awt.Component;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.awt.event.FocusAdapter;
import java.awt.event.FocusEvent;
import java.awt.event.MouseAdapter;
import java.awt.event.MouseEvent;
import java.util.Vector;
import javax.swing.JOptionPane;
import javax.swing.JRadioButton;
import javax.swing.JTextField;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author frsy
 */
public class FrmManage extends javax.swing.JFrame {

    /**
     * Creates new form FrmManage
     */
    private Vector title = new Vector();
    private String[] titles = {"快递单号","取件码","位置","入柜时间","出柜时间","用户手机号"};
    private DefaultTableModel dtm = new DefaultTableModel(){

        @Override
        public boolean isCellEditable(int row, int column) {
            return false;
        }
        
    };
    public FrmManage() {
        initComponents();
        for(String ts:titles){
            title.add(ts);
        }        
        flushTable();
        jTable1.addMouseListener(new MouseAdapter() {

            @Override
            public void mouseClicked(MouseEvent e) {
                unlock();
                int row = jTable1.getSelectedRow();
                Vector vPkg;
                vPkg = (Vector)dtm.getDataVector().get(row);
                txtPkgId.setText((String)vPkg.get(0));
                txtPkgCode.setText((String)vPkg.get(1));
                txtPos.setText((String)vPkg.get(2));
                txtInDate.setText((String)vPkg.get(3));
                txtOutDate.setText((String)vPkg.get(4));
                txtUserNum.setText((String)vPkg.get(5));
            }
            
        });
        
        Component[] cps = pnlSelect.getComponents();
        for(Component cp:cps){
            if(cp instanceof JTextField){
                ((JTextField)cp).addFocusListener(new FocusAdapter() {

                    @Override
                    public void focusGained(FocusEvent e) {
                        clearSlt();
                    }
                    
                });
            }
            if(cp instanceof JRadioButton){
                ((JRadioButton)cp).addActionListener(new ActionListener() {

                    @Override
                    public void actionPerformed(ActionEvent e) {
                        Vector vp = new Vector();
                        txtNum.setText(null);
                        txtPid.setText(null);
                        if(rbtin.isSelected()){
                            vp = DBConn.queryPackageByState(DBConn.PACKAGE_STATE_IN);
                        }else{
                            vp = DBConn.queryPackageByState(DBConn.PACKAGE_STATE_OUT);
                        }
                        flushTable(vp);
                    }
                });
            }
        }
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btngroupState = new javax.swing.ButtonGroup();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable(dtm);
        txtPkgId = new javax.swing.JTextField();
        txtPkgCode = new javax.swing.JTextField();
        txtPos = new javax.swing.JTextField();
        txtInDate = new javax.swing.JTextField();
        txtOutDate = new javax.swing.JTextField();
        txtUserNum = new javax.swing.JTextField();
        lblPkgId = new javax.swing.JLabel();
        lblPkgCode = new javax.swing.JLabel();
        lblPos = new javax.swing.JLabel();
        lblInDate = new javax.swing.JLabel();
        lblOutDate = new javax.swing.JLabel();
        lblUserName = new javax.swing.JLabel();
        btnSout = new javax.swing.JButton();
        btnDel = new javax.swing.JButton();
        btnUpd = new javax.swing.JButton();
        btnNewCode = new javax.swing.JButton();
        pnlSelect = new javax.swing.JPanel();
        lblNum = new javax.swing.JLabel();
        txtPid = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        rbtin = new javax.swing.JRadioButton();
        rbtout = new javax.swing.JRadioButton();
        txtNum = new javax.swing.JTextField();
        lblId = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenuItem2 = new javax.swing.JMenuItem();
        jMenuItem4 = new javax.swing.JMenuItem();
        jMenuItem3 = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("快递管理");

        jTable1.setModel(dtm);
        jScrollPane1.setViewportView(jTable1);

        txtPkgId.setEditable(false);

        txtPkgCode.setEditable(false);

        txtPos.setEditable(false);

        txtInDate.setEditable(false);

        txtOutDate.setEditable(false);

        lblPkgId.setFont(new java.awt.Font("宋体", 0, 14)); // NOI18N
        lblPkgId.setText("快递单号");

        lblPkgCode.setFont(new java.awt.Font("宋体", 0, 14)); // NOI18N
        lblPkgCode.setText("取件码");

        lblPos.setFont(new java.awt.Font("宋体", 0, 14)); // NOI18N
        lblPos.setText("快递位置");

        lblInDate.setFont(new java.awt.Font("宋体", 0, 14)); // NOI18N
        lblInDate.setText("入柜日期");

        lblOutDate.setFont(new java.awt.Font("宋体", 0, 14)); // NOI18N
        lblOutDate.setText("出柜日期");

        lblUserName.setFont(new java.awt.Font("宋体", 0, 14)); // NOI18N
        lblUserName.setText("手机号码");

        btnSout.setText("出柜");
        btnSout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSoutActionPerformed(evt);
            }
        });

        btnDel.setText("删除");
        btnDel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDelActionPerformed(evt);
            }
        });

        btnUpd.setText("修改");
        btnUpd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUpdActionPerformed(evt);
            }
        });

        btnNewCode.setText("生成新取件码");
        btnNewCode.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNewCodeActionPerformed(evt);
            }
        });

        lblNum.setText("手机号");

        jButton1.setText("筛选");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        btngroupState.add(rbtin);
        rbtin.setText("未出柜");

        btngroupState.add(rbtout);
        rbtout.setText("已出柜");

        lblId.setText("快递单号");

        javax.swing.GroupLayout pnlSelectLayout = new javax.swing.GroupLayout(pnlSelect);
        pnlSelect.setLayout(pnlSelectLayout);
        pnlSelectLayout.setHorizontalGroup(
            pnlSelectLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlSelectLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(pnlSelectLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(pnlSelectLayout.createSequentialGroup()
                        .addGroup(pnlSelectLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblNum)
                            .addComponent(lblId))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(pnlSelectLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtPid, javax.swing.GroupLayout.DEFAULT_SIZE, 123, Short.MAX_VALUE)
                            .addComponent(txtNum))
                        .addGap(3, 3, 3))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlSelectLayout.createSequentialGroup()
                        .addGroup(pnlSelectLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jButton1)
                            .addGroup(pnlSelectLayout.createSequentialGroup()
                                .addComponent(rbtin)
                                .addGap(65, 65, 65)
                                .addComponent(rbtout)))
                        .addGap(33, 33, 33))))
        );
        pnlSelectLayout.setVerticalGroup(
            pnlSelectLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlSelectLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlSelectLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblNum)
                    .addComponent(txtNum, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(10, 10, 10)
                .addGroup(pnlSelectLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtPid, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblId))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton1)
                .addGap(46, 46, 46)
                .addGroup(pnlSelectLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(rbtin)
                    .addComponent(rbtout)))
        );

        jMenu1.setText("系统");

        jMenuItem1.setText("快递入柜");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem1);

        jMenuItem2.setText("注册管理员帐号");
        jMenuItem2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem2ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem2);

        jMenuItem4.setText("返回取件");
        jMenuItem4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem4ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem4);

        jMenuItem3.setText("退出");
        jMenuItem3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem3ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem3);

        jMenuBar1.add(jMenu1);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblPkgId)
                            .addComponent(lblPkgCode)
                            .addComponent(lblPos)
                            .addComponent(lblInDate, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(lblOutDate, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(lblUserName, javax.swing.GroupLayout.Alignment.TRAILING))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtPos, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtPkgCode, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                    .addComponent(txtPkgId, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(449, 449, 449))
                                .addGroup(layout.createSequentialGroup()
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                            .addComponent(txtOutDate, javax.swing.GroupLayout.DEFAULT_SIZE, 150, Short.MAX_VALUE)
                                            .addComponent(txtInDate))
                                        .addComponent(txtUserNum, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGap(138, 138, 138)))))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane1)
                        .addContainerGap())
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnSout)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnDel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnUpd)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnNewCode)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(pnlSelect, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(26, 26, 26))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtPkgId, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblPkgId))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtPkgCode, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblPkgCode))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtPos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblPos))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtInDate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblInDate))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtOutDate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblOutDate))
                        .addGap(8, 8, 8)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtUserNum, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblUserName))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnSout)
                            .addComponent(btnDel)
                            .addComponent(btnUpd)
                            .addComponent(btnNewCode))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 10, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(pnlSelect, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(18, 18, 18)))
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 275, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void flushTable(Vector vp){
        dtm.setDataVector(vp, title);
        jTable1.getColumnModel().getColumn(0).setPreferredWidth(50);
        jTable1.getColumnModel().getColumn(1).setPreferredWidth(15);
        jTable1.getColumnModel().getColumn(2).setPreferredWidth(15);
        jTable1.getColumnModel().getColumn(3).setPreferredWidth(85);
        jTable1.getColumnModel().getColumn(4).setPreferredWidth(85);
        jTable1.getColumnModel().getColumn(5).setPreferredWidth(50);
        clearInfo();
        lock();
    }
    
    private void flushTable(){
        dtm.setDataVector(DBConn.queryPackage(), title);
        jTable1.getColumnModel().getColumn(0).setPreferredWidth(50);
        jTable1.getColumnModel().getColumn(1).setPreferredWidth(15);
        jTable1.getColumnModel().getColumn(2).setPreferredWidth(15);
        jTable1.getColumnModel().getColumn(3).setPreferredWidth(85);
        jTable1.getColumnModel().getColumn(4).setPreferredWidth(85);
        jTable1.getColumnModel().getColumn(5).setPreferredWidth(50);
        clearInfo();
        lock();
    }
    
    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        new FrmPis(this).setVisible(true);
        this.setEnabled(false);
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        Vector vp = new Vector();
        if(!txtNum.getText().equals("")){
            vp = DBConn.queryPackageByNum(txtNum.getText());
        }else{
            System.out.println("test");
            vp = DBConn.queryPackageById(txtPid.getText());
        }
        flushTable(vp);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void btnSoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSoutActionPerformed
        if(((String)((Vector)dtm.getDataVector().get(jTable1.getSelectedRow())).get(4)).equals("未取件")){
            DBConn.stkOutPackage((String)((Vector)dtm.getDataVector().get(jTable1.getSelectedRow())).get(1));
            JOptionPane.showMessageDialog(null,"快递出柜成功","提示",JOptionPane.INFORMATION_MESSAGE);
            flushTable();
        }else{
            JOptionPane.showMessageDialog(null,"快递已出柜","错误",JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_btnSoutActionPerformed

    private void btnDelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDelActionPerformed
        int conf = JOptionPane.showConfirmDialog(null,"您确认要删除此快递信息吗？","警告",JOptionPane.OK_CANCEL_OPTION, JOptionPane.INFORMATION_MESSAGE);
        if(conf==JOptionPane.OK_OPTION && !((String)((Vector)dtm.getDataVector().get(jTable1.getSelectedRow())).get(4)).equals("未取件")){
            if(DBConn.deletePackage((String)((Vector)dtm.getDataVector().get(jTable1.getSelectedRow())).get(0))){
                JOptionPane.showMessageDialog(null,"删除成功","提示",JOptionPane.INFORMATION_MESSAGE);
            }else{
                JOptionPane.showMessageDialog(null,"删除失败","提示",JOptionPane.INFORMATION_MESSAGE);
            }
        }else if(conf!=JOptionPane.CANCEL_OPTION){
            JOptionPane.showMessageDialog(null,"请勿删除未出库的快递","错误",JOptionPane.ERROR_MESSAGE);
        }
        flushTable();
    }//GEN-LAST:event_btnDelActionPerformed

    private void btnUpdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUpdActionPerformed
        String nNum = txtUserNum.getText();
        if(nNum.matches("^1[34578]\\d{9}")){
            if(DBConn.updateUserNum((String)((Vector)dtm.getDataVector().get(jTable1.getSelectedRow())).get(0),nNum)){
                JOptionPane.showMessageDialog(null,"修改成功","提示",JOptionPane.INFORMATION_MESSAGE);
             }else{
                JOptionPane.showMessageDialog(null,"修改失败","提示",JOptionPane.INFORMATION_MESSAGE);
            }
        }else{
            JOptionPane.showMessageDialog(null,"请输入正确的11位手机号","提示",JOptionPane.INFORMATION_MESSAGE);
        }
        flushTable();
    }//GEN-LAST:event_btnUpdActionPerformed

    private void btnNewCodeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNewCodeActionPerformed
        if(((String)((Vector)dtm.getDataVector().get(jTable1.getSelectedRow())).get(4)).equals("未取件")){
            if(DBConn.renewPackageCode((String)((Vector)dtm.getDataVector().get(jTable1.getSelectedRow())).get(0))){
                JOptionPane.showMessageDialog(null,"更新取件码成功","提示",JOptionPane.INFORMATION_MESSAGE);
             }else{
                JOptionPane.showMessageDialog(null,"更新取件码失败","提示",JOptionPane.INFORMATION_MESSAGE);
            }
        }else{
            JOptionPane.showMessageDialog(null,"快递已出柜，无法更新取件码","错误",JOptionPane.ERROR_MESSAGE);
        }
        
        flushTable();
    }//GEN-LAST:event_btnNewCodeActionPerformed

    private void jMenuItem3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem3ActionPerformed
        this.dispose();
        System.exit(0);
    }//GEN-LAST:event_jMenuItem3ActionPerformed

    private void jMenuItem2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem2ActionPerformed
        new FrmSignup(this).setVisible(true);
        this.setEnabled(false);
    }//GEN-LAST:event_jMenuItem2ActionPerformed

    private void jMenuItem4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem4ActionPerformed
        new FrmMain().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jMenuItem4ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrmManage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrmManage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrmManage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrmManage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrmManage().setVisible(true);
            }
        });
    }
    
    private void clearInfo(){
        txtPkgId.setText(null);
        txtPkgCode.setText(null);
        txtPos.setText(null);
        txtInDate.setText(null);
        txtOutDate.setText(null);
        txtUserNum.setText(null);
    }
    
    private void clearSlt(){
        txtPid.setText(null);
        txtNum.setText(null);
        rbtin.setSelected(false);
        btngroupState.clearSelection();
        flushTable();
    }
    
    private void unlock(){
        btnSout.setEnabled(true);
        btnDel.setEnabled(true);
        btnUpd.setEnabled(true);
        btnNewCode.setEnabled(true);
    }
    
    private void lock(){
        btnSout.setEnabled(false);
        btnDel.setEnabled(false);
        btnUpd.setEnabled(false);
        btnNewCode.setEnabled(false);
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnDel;
    private javax.swing.JButton btnNewCode;
    private javax.swing.JButton btnSout;
    private javax.swing.JButton btnUpd;
    private javax.swing.ButtonGroup btngroupState;
    private javax.swing.JButton jButton1;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JMenuItem jMenuItem4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JLabel lblId;
    private javax.swing.JLabel lblInDate;
    private javax.swing.JLabel lblNum;
    private javax.swing.JLabel lblOutDate;
    private javax.swing.JLabel lblPkgCode;
    private javax.swing.JLabel lblPkgId;
    private javax.swing.JLabel lblPos;
    private javax.swing.JLabel lblUserName;
    private javax.swing.JPanel pnlSelect;
    private javax.swing.JRadioButton rbtin;
    private javax.swing.JRadioButton rbtout;
    private javax.swing.JTextField txtInDate;
    private javax.swing.JTextField txtNum;
    private javax.swing.JTextField txtOutDate;
    private javax.swing.JTextField txtPid;
    private javax.swing.JTextField txtPkgCode;
    private javax.swing.JTextField txtPkgId;
    private javax.swing.JTextField txtPos;
    private javax.swing.JTextField txtUserNum;
    // End of variables declaration//GEN-END:variables
}
